//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
)

func main() {
	log.SetFlags(0)

	content := bytes.Buffer{}
	err := generateTable(content)
	if err != nil {
		log.Fatal(err)
	}
	content2 := content.String()
	content3, err := gofmt(content2)
	if err != nil {
		log.Fatal(err)
	}
	err = os.WriteFile("table.go", []byte(content3), 0644)
	if err != nil {
		log.Fatal(err)
	}
}

func generateTable(w io.Writer) error {
	fmt.Fprintf(w, `// Code generated by gen.go. DO NOT EDIT.`+"\n")
	fmt.Fprintln(w)
	fmt.Fprintf(w, `var stateChanges [16][256]uint8 = {`+"\n")
	for state, entries := range stateChanges {

	}
	fmt.Fprintf(w, `}`+"\n")
	return nil
}
