name: "anstyle: go test"
on:
  push:
    branches: ["main"]
    paths:
      - anstyle/**
      - "!anstyle/README.md"
      - "!anstyle/LICENSE"
      - "!anstyle/.gitignore"
  pull_request:
    branches: ["main"]
    paths:
      - anstyle/**
      - "!anstyle/README.md"
      - "!anstyle/LICENSE"
      - "!anstyle/.gitignore"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: anstyle/go.mod
      - run: go test -v
        working-directory: anstyle